//! The register of configuration keys the control plane reads itself.

use crate::capabilities::config::ConfigField;

use super::fields::{
    ALERT_CHANNELS_CONFIG, ALERT_EMAIL_FROM_CONFIG, ALERT_EMAIL_TO_CONFIG,
    ALERT_RESEND_FIELD_CONFIG, ALERT_RESEND_ITEM_CONFIG, ALERT_SKARBIEC_CONSUMER_CONFIG,
    ALERT_SKARBIEC_TOKEN_FILE_CONFIG, API_URL_CONFIG, CREDENTIALS_ADMIN_CONSUMER_CONFIG,
    CREDENTIALS_ADMIN_TOKEN_FILE_CONFIG, CREDENTIALS_ADMIN_URL_CONFIG, CREDENTIALS_STORE_CONFIG,
    DASHBOARD_BIND_CONFIG, DASHBOARD_PORT_CONFIG, DEPLOYMENT_ID_CONFIG, DISABLED_PROVIDERS_CONFIG,
    PROVIDERS_CONFIG, RELEASE_AGENT_RUNTIME_BUNDLE_SHA256_CONFIG,
    RELEASE_AGENT_RUNTIME_BUNDLE_URI_CONFIG, RELEASE_PLATFORM_CONFIG,
    RELEASE_SIGNING_KEY_ID_CONFIG, RELEASE_SIGNING_KEY_ITEM_CONFIG, RELEASE_VERSION_CONFIG,
    SKARBIEC_VAULT_FILE_CONFIG, STORAGE_BACKEND_CONFIG,
};
use super::skarbiec::{
    AGENT_SKARBIEC, AGENT_SKARBIEC_ITEMS_CONFIG, AGENT_SKARBIEC_SECRET_FIELDS_CONFIG,
    BACKEND_MESSAGING_SKARBIEC, BACKEND_MESSAGING_SKARBIEC_ITEMS_CONFIG,
    INTEGRATION_CLIENTS_CONFIG, INTEGRATION_PROVIDERS_CONFIG,
    INTEGRATION_PROVIDER_SKARBIEC_URL_CONFIG, INTEGRATION_SKARBIEC, MACHINE_API_CLIENTS_CONFIG,
    MACHINE_API_SKARBIEC, OBJECT_API_NAMESPACES_CONFIG, OBJECT_API_SKARBIEC,
    RATE_LIMIT_CLIENTS_CONFIG, RATE_LIMIT_SKARBIEC, RELEASE_API_PUBLISHERS_CONFIG,
    RELEASE_API_SKARBIEC, SECRETS_SKARBIEC, SERVICE_API_DEPLOYERS_CONFIG, SERVICE_API_SKARBIEC,
};

/// Every configuration key the control plane reads itself, as opposed to the
/// keys an adapter reads on its behalf — those hang off
/// [`CapabilityVariant::config`] and are reachable through [`config_field`].
///
/// This list is the register of readers, and it is exhaustive on purpose.
/// `storage.stado.ca_file` showed what the alternative costs: a key an operator
/// wrote, `config validate` accepted, `doctor` blessed, and no code path ever
/// consulted, for months. A setting reaches this binary only through
/// [`crate::config_file::field_value`], which takes a catalogued field and not a
/// dotted string, so a key absent from here and from a variant's `config` is a
/// key that cannot be read — and one that validation is free to call out.
pub const CONTROL_CONFIG: &[ConfigField] = &[
    PROVIDERS_CONFIG,
    DISABLED_PROVIDERS_CONFIG,
    STORAGE_BACKEND_CONFIG,
    CREDENTIALS_STORE_CONFIG,
    CREDENTIALS_ADMIN_URL_CONFIG,
    CREDENTIALS_ADMIN_CONSUMER_CONFIG,
    CREDENTIALS_ADMIN_TOKEN_FILE_CONFIG,
    API_URL_CONFIG,
    DEPLOYMENT_ID_CONFIG,
    RELEASE_VERSION_CONFIG,
    RELEASE_PLATFORM_CONFIG,
    RELEASE_SIGNING_KEY_ID_CONFIG,
    RELEASE_SIGNING_KEY_ITEM_CONFIG,
    RELEASE_AGENT_RUNTIME_BUNDLE_URI_CONFIG,
    RELEASE_AGENT_RUNTIME_BUNDLE_SHA256_CONFIG,
    ALERT_CHANNELS_CONFIG,
    ALERT_EMAIL_TO_CONFIG,
    ALERT_EMAIL_FROM_CONFIG,
    ALERT_RESEND_ITEM_CONFIG,
    ALERT_RESEND_FIELD_CONFIG,
    ALERT_SKARBIEC_CONSUMER_CONFIG,
    ALERT_SKARBIEC_TOKEN_FILE_CONFIG,
    DASHBOARD_BIND_CONFIG,
    DASHBOARD_PORT_CONFIG,
    SECRETS_SKARBIEC.url,
    SECRETS_SKARBIEC.consumer,
    SECRETS_SKARBIEC.token_file,
    SKARBIEC_VAULT_FILE_CONFIG,
    AGENT_SKARBIEC.url,
    AGENT_SKARBIEC.consumer,
    AGENT_SKARBIEC.token_file,
    AGENT_SKARBIEC_ITEMS_CONFIG,
    AGENT_SKARBIEC_SECRET_FIELDS_CONFIG,
    OBJECT_API_SKARBIEC.url,
    OBJECT_API_SKARBIEC.consumer,
    OBJECT_API_SKARBIEC.token_file,
    OBJECT_API_NAMESPACES_CONFIG,
    RELEASE_API_SKARBIEC.url,
    RELEASE_API_SKARBIEC.consumer,
    RELEASE_API_SKARBIEC.token_file,
    RELEASE_API_PUBLISHERS_CONFIG,
    MACHINE_API_SKARBIEC.url,
    MACHINE_API_SKARBIEC.consumer,
    MACHINE_API_SKARBIEC.token_file,
    MACHINE_API_CLIENTS_CONFIG,
    SERVICE_API_SKARBIEC.url,
    SERVICE_API_SKARBIEC.consumer,
    SERVICE_API_SKARBIEC.token_file,
    SERVICE_API_DEPLOYERS_CONFIG,
    RATE_LIMIT_SKARBIEC.url,
    RATE_LIMIT_SKARBIEC.consumer,
    RATE_LIMIT_SKARBIEC.token_file,
    RATE_LIMIT_CLIENTS_CONFIG,
    INTEGRATION_SKARBIEC.url,
    INTEGRATION_SKARBIEC.consumer,
    INTEGRATION_SKARBIEC.token_file,
    INTEGRATION_PROVIDER_SKARBIEC_URL_CONFIG,
    INTEGRATION_CLIENTS_CONFIG,
    INTEGRATION_PROVIDERS_CONFIG,
    BACKEND_MESSAGING_SKARBIEC.url,
    BACKEND_MESSAGING_SKARBIEC.consumer,
    BACKEND_MESSAGING_SKARBIEC.token_file,
    BACKEND_MESSAGING_SKARBIEC_ITEMS_CONFIG,
];
