//! The configuration the control plane reads itself: its own keys, the
//! Skarbiec boundaries they bind, and the register of every one of them.

mod fields;
mod list;
mod skarbiec;

pub use fields::{
    ALERT_CHANNELS_CONFIG, ALERT_EMAIL_FROM_CONFIG, ALERT_EMAIL_TO_CONFIG,
    ALERT_RESEND_FIELD_CONFIG, ALERT_RESEND_ITEM_CONFIG, ALERT_SKARBIEC_CONSUMER_CONFIG,
    ALERT_SKARBIEC_TOKEN_FILE_CONFIG, API_URL_CONFIG, CREDENTIALS_ADMIN_CONSUMER_CONFIG,
    CREDENTIALS_ADMIN_TOKEN_FILE_CONFIG, CREDENTIALS_ADMIN_URL_CONFIG, CREDENTIALS_STORE_CONFIG,
    DASHBOARD_BIND_CONFIG, DASHBOARD_PORT_CONFIG, DEPLOYMENT_ID_CONFIG, DISABLED_PROVIDERS_CONFIG,
    PROVIDERS_CONFIG, RELEASE_AGENT_RUNTIME_BUNDLE_SHA256_CONFIG,
    RELEASE_AGENT_RUNTIME_BUNDLE_URI_CONFIG, RELEASE_PLATFORM_CONFIG,
    RELEASE_SIGNING_KEY_ID_CONFIG, RELEASE_SIGNING_KEY_ITEM_CONFIG, RELEASE_VERSION_CONFIG,
    SKARBIEC_VAULT_FILE_CONFIG, STORAGE_BACKEND_CONFIG,
};
pub use list::CONTROL_CONFIG;
pub use skarbiec::{
    SkarbiecBinding, AGENT_SKARBIEC, AGENT_SKARBIEC_ITEMS_CONFIG,
    AGENT_SKARBIEC_SECRET_FIELDS_CONFIG, BACKEND_MESSAGING_SKARBIEC,
    BACKEND_MESSAGING_SKARBIEC_ITEMS_CONFIG, DATABASE_API_DATABASES_CONFIG,
    INTEGRATION_CLIENTS_CONFIG, INTEGRATION_PROVIDERS_CONFIG,
    INTEGRATION_PROVIDER_SKARBIEC_URL_CONFIG, INTEGRATION_SKARBIEC, MACHINE_API_CLIENTS_CONFIG,
    MACHINE_API_SKARBIEC, OBJECT_API_NAMESPACES_CONFIG, OBJECT_API_SKARBIEC,
    RATE_LIMIT_CLIENTS_CONFIG, RATE_LIMIT_SKARBIEC, RELEASE_API_PUBLISHERS_CONFIG,
    RELEASE_API_SKARBIEC, SECRETS_SKARBIEC, SERVICE_API_DEPLOYERS_CONFIG, SERVICE_API_SKARBIEC,
    WEB_API_PRODUCTS_CONFIG,
};
