use crate::{
    common::{sha256, xml, Runtime},
    paths, signing,
};
use anyhow::{bail, Result};
use std::path::PathBuf;

pub const INTERVAL_SECONDS: u32 = 3600;
#[derive(Clone, Copy)]
pub enum Surface {
    Cli,
    Desktop,
}
impl Surface {
    pub fn name(self) -> &'static str {
        match self {
            Self::Cli => "cli",
            Self::Desktop => "desktop",
        }
    }
    pub fn label(self) -> &'static str {
        match self {
            Self::Cli => "com.wisent.products.cli-sync",
            Self::Desktop => "com.wisent.products.desktop-sync",
        }
    }
    pub fn path(self, runtime: &Runtime) -> PathBuf {
        runtime
            .home
            .join("Library/LaunchAgents")
            .join(format!("{}.plist", self.label()))
    }
}

/// The installed Stado every scheduled sweep runs, as `stado product sync`.
fn installed(runtime: &Runtime) -> PathBuf {
    runtime.home.join(".stado/bin/stado")
}

pub fn executable(runtime: &Runtime) -> Result<PathBuf> {
    let installed = installed(runtime);
    if !paths::executable(&installed) || !signing::native(&installed)? {
        bail!("{} is not an installed native Stado executable; install Stado before scheduling product updates", installed.display());
    }
    if sha256(&installed)? != sha256(&std::env::current_exe()?)? {
        bail!("the installed Stado executable differs from this process; schedule through the installed Stado");
    }
    let signature = signing::inspect(&installed)?;
    if !signing::acceptable(&signature) {
        bail!("installed scheduler has no stable code identity: {signature}");
    }
    Ok(installed)
}

pub fn render(runtime: &Runtime, surface: Surface) -> Result<String> {
    let executable = installed(runtime);
    let mut directories = vec![
        runtime.home.join(".local/bin"),
        runtime.home.join(".stado/bin"),
        runtime.home.join(".cargo/bin"),
    ];
    directories.extend(
        [
            "/opt/homebrew/bin",
            "/usr/local/bin",
            "/usr/bin",
            "/bin",
            "/usr/sbin",
            "/sbin",
        ]
        .map(PathBuf::from),
    );
    let path = std::env::join_paths(directories)?
        .to_string_lossy()
        .into_owned();
    let log = runtime.home.join("Library/Logs/wisent");
    let mut argv = vec![
        executable.to_string_lossy().into_owned(),
        "product".to_owned(),
    ];
    if !runtime.embedded_catalog {
        argv.extend([
            "--catalog".to_owned(),
            runtime.catalog.to_string_lossy().into_owned(),
        ]);
    }
    argv.extend([
        "sync".to_owned(),
        "--surface".to_owned(),
        surface.name().to_owned(),
        "--fetch".to_owned(),
    ]);
    let argv = argv
        .iter()
        .map(|value| format!("<string>{}</string>", xml(value)))
        .collect::<String>();
    Ok(format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>Label</key><string>{label}</string>
<!-- Generated by stado product schedule --install from stado-rs/product/src/schedule/definition.rs.
Only canonical main checkouts are used. Dirty or divergent sources stay held.
The shared sweep lock prevents overlapping CLI and desktop builds. -->
<key>ProgramArguments</key><array>{argv}</array>
<key>EnvironmentVariables</key><dict>
<key>HOME</key><string>{home}</string>
<key>WISENT_WORKSPACE</key><string>{workspace}</string>
<key>WISENT_OUTPUT_DIR</key><string>{output}</string>
<key>PATH</key><string>{path}</string>
<key>GIT_TERMINAL_PROMPT</key><string>0</string>
</dict>
<key>RunAtLoad</key><true/>
<key>StartInterval</key><integer>{interval}</integer>
<key>ProcessType</key><string>Background</string>
<key>Nice</key><integer>5</integer>
<key>LowPriorityIO</key><true/>
<key>ThrottleInterval</key><integer>60</integer>
<key>StandardOutPath</key><string>{stdout}</string>
<key>StandardErrorPath</key><string>{stderr}</string>
</dict></plist>
"#,
        label = surface.label(),
        home = xml(&runtime.home.to_string_lossy()),
        workspace = xml(&runtime.workspace.to_string_lossy()),
        output = xml(&runtime.output.to_string_lossy()),
        path = xml(&path),
        interval = INTERVAL_SECONDS,
        stdout = xml(&log
            .join(format!("{}-sync.log", surface.name()))
            .to_string_lossy()),
        stderr = xml(&log
            .join(format!("{}-sync.error.log", surface.name()))
            .to_string_lossy())
    ))
}
