//! `stado product catalog --names [ORG]`: the name register (`~/NAMES.md`),
//! one row per active repository of the organization as GitHub lists it,
//! with the repository's own GitHub description and, where the catalog
//! claims it, the product it belongs to. A deleted or archived repository
//! leaves the register the next time it is generated; a repository with no
//! description is listed anyway, because a name nobody can look up is the
//! failure the register exists to prevent.

use crate::common::checked;
use anyhow::{Context, Result};
use serde_json::Value;
use std::collections::BTreeMap;
use std::process::Command;

const PREAMBLE: &str = "# Wisent name register

Generated by `stado product catalog --names --output ~/NAMES.md` from the
organization's repositories on GitHub and Stado's product catalog. Do not edit
by hand: change the repository's description on GitHub, or the product's record
through `stado product registry`, then regenerate.

**These are product names, not words.** Nearly all of them are ordinary Polish
nouns. `brama` is not \"gate\", `oko` is not \"eye\", `most` is not \"bridge\", `las`
is not \"forest\", `stado` is not \"herd\", `skarbiec` is not \"vault\", `jeden` is
not \"one\", `tama` is not \"dam\", `probierz` is not \"touchstone\". If a sentence
still makes sense after you translate one of these, you have misread it.

When the user names something you do not recognise, look it up here before
answering. An answer built on a guessed name is wrong even when it is coherent.

This is the canonical register of **names**, not the canonical list of products.
Product identity, status, owner and surfaces live in
`stado/catalog/products.yml`. A repository appearing below does not make it a
product; the product column names the catalog record that claims it.

Each name is a repository as GitHub names it, not a directory on this machine:
a local directory can be called anything, so a directory name is not evidence
of what a repository is.

| name | product | what it is |
|---|---|---|
";

/// Which catalog product claims each repository (`owner/name`).
fn owners(document: &Value) -> Result<BTreeMap<String, String>> {
    let mut owners = BTreeMap::new();
    for product in document["products"]
        .as_array()
        .context("products must be a list")?
    {
        let id = super::text(product, "id")?.to_owned();
        owners.insert(
            super::text(product, "owner_repository")?.to_owned(),
            id.clone(),
        );
        for surface in product["surfaces"]
            .as_array()
            .context("surfaces must be a list")?
        {
            owners
                .entry(super::text(surface, "repository")?.to_owned())
                .or_insert_with(|| id.clone());
        }
    }
    Ok(owners)
}

fn cell(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The register for `org`, as Markdown.
pub fn register(document: &Value, org: &str) -> Result<String> {
    let output = checked(Command::new("gh").args([
        "repo",
        "list",
        org,
        "--limit",
        "10000",
        "--json",
        "nameWithOwner,name,description,isArchived",
    ]))?;
    let mut repositories: Vec<Value> = serde_json::from_slice(&output.stdout)
        .context("gh repo list answered something other than a JSON list")?;
    repositories.retain(|repository| repository["isArchived"] != true);
    repositories.sort_by(|a, b| a["name"].as_str().cmp(&b["name"].as_str()));
    let owners = owners(document)?;
    let mut register = PREAMBLE.to_owned();
    for repository in &repositories {
        let name = repository["name"]
            .as_str()
            .context("a repository has no name")?;
        let full = repository["nameWithOwner"].as_str().unwrap_or(name);
        let product = owners
            .get(full)
            .map_or(String::new(), |id| format!("`{id}`"));
        let description = match repository["description"].as_str().map(str::trim) {
            Some(text) if !text.is_empty() => cell(text),
            _ => "(no description on GitHub)".to_owned(),
        };
        register.push_str(&format!("| `{name}` | {product} | {description} |\n"));
    }
    Ok(register)
}
