//! Compute, storage, execution and scheduling variants.

use crate::capabilities::catalog::ProviderId;
use crate::capabilities::config::variants::{
    AWS_COMPUTE_CONFIG, AZURE_COMPUTE_CONFIG, AZURE_STORAGE_CONFIG, GCP_COMPUTE_CONFIG, GCS_CONFIG,
    LOCAL_STORAGE_CONFIG, S3_CONFIG, STADO_OBJECT_STORAGE_CONFIG,
};
use crate::capabilities::registry::CapabilityVariant;
use crate::capabilities::runtime::{
    ComputeAdapter, ExecutionAdapter, GpuCloudVendor, RuntimeAdapter, StorageAdapter,
};

/// A GPU cloud vendor as a machine-provisioning variant: its id is the
/// provider id, its settings and summary come from the vendor's profile.
const fn gpu_cloud_compute(vendor: GpuCloudVendor) -> CapabilityVariant {
    let profile = crate::providers::gpu_cloud::profile(vendor);
    CapabilityVariant {
        id: vendor.provider().as_str(),
        aliases: vendor.provider().aliases(),
        provider: Some(vendor.provider()),
        implementation: "providers::gpu_cloud::GpuCloudProvider",
        summary: profile.summary,
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::GpuCloud(vendor)),
        config: profile.config,
    }
}

/// The ephemeral agent a GPU cloud vendor's machine runs.
const fn gpu_cloud_execution(vendor: GpuCloudVendor) -> CapabilityVariant {
    CapabilityVariant {
        id: vendor.provider().as_str(),
        aliases: vendor.provider().aliases(),
        provider: Some(vendor.provider()),
        implementation: "providers::local::agent + monitor::reap + providers::gpu_cloud",
        summary: "Ephemeral agent running on a machine rented from this GPU cloud vendor.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::GpuCloud(vendor)),
        config: crate::providers::gpu_cloud::profile(vendor).config,
    }
}

pub(in crate::capabilities::registry) const COMPUTE: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: ProviderId::Gcp.as_str(),
        aliases: ProviderId::Gcp.aliases(),
        provider: Some(ProviderId::Gcp),
        implementation: "providers::gcp::GcpProvider",
        summary: "Provision and reap Google Compute Engine instances.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::Gcp),
        config: GCP_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Azure.as_str(),
        aliases: ProviderId::Azure.aliases(),
        provider: Some(ProviderId::Azure),
        implementation: "providers::azure::AzureProvider",
        summary: "Provision and reap Azure virtual machines.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::Azure),
        config: AZURE_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Aws.as_str(),
        aliases: ProviderId::Aws.aliases(),
        provider: Some(ProviderId::Aws),
        implementation: "providers::aws::AwsProvider",
        summary: "Provision and reap Amazon EC2 instances.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::Aws),
        config: AWS_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Box.as_str(),
        aliases: ProviderId::Box.aliases(),
        provider: Some(ProviderId::Box),
        implementation: "providers::box::BoxProvider",
        summary: "Lease externally managed fixed-shape boxes.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::Box),
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Local.as_str(),
        aliases: ProviderId::Local.aliases(),
        provider: Some(ProviderId::Local),
        implementation: "providers::local",
        summary: "Execute on an existing local host without VM provisioning.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::ExistingHost),
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Vast.as_str(),
        aliases: ProviderId::Vast.aliases(),
        provider: Some(ProviderId::Vast),
        implementation: "providers::vast",
        summary: "Publish and manage a Vast.ai host; not a renter provisioner.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::Compute(ComputeAdapter::VastHost),
        config: &[],
    },
    gpu_cloud_compute(GpuCloudVendor::Arkane),
    gpu_cloud_compute(GpuCloudVendor::Crusoe),
    gpu_cloud_compute(GpuCloudVendor::Cudo),
    gpu_cloud_compute(GpuCloudVendor::Hyperstack),
    gpu_cloud_compute(GpuCloudVendor::Lambda),
    gpu_cloud_compute(GpuCloudVendor::Latitude),
    gpu_cloud_compute(GpuCloudVendor::Nebius),
    gpu_cloud_compute(GpuCloudVendor::Oblivus),
    gpu_cloud_compute(GpuCloudVendor::Oracle),
    gpu_cloud_compute(GpuCloudVendor::Runpod),
    gpu_cloud_compute(GpuCloudVendor::Salad),
    gpu_cloud_compute(GpuCloudVendor::Scaleway),
    gpu_cloud_compute(GpuCloudVendor::VoltagePark),
    gpu_cloud_compute(GpuCloudVendor::Vultr),
];

pub(in crate::capabilities::registry) const STORAGE: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: StorageAdapter::Gcs.id(),
        aliases: &[],
        provider: Some(ProviderId::Gcp),
        implementation: "queue::gcs::GcsBackend",
        summary: "Shared Google Cloud Storage queue and object store.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Storage(StorageAdapter::Gcs),
        config: GCS_CONFIG,
    },
    CapabilityVariant {
        id: StorageAdapter::AzureBlob.id(),
        aliases: &[],
        provider: Some(ProviderId::Azure),
        implementation: "queue::azure_blob::AzureBlobBackend",
        summary: "Shared Azure Blob queue and object store.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Storage(StorageAdapter::AzureBlob),
        config: AZURE_STORAGE_CONFIG,
    },
    CapabilityVariant {
        id: StorageAdapter::S3.id(),
        aliases: &[],
        provider: Some(ProviderId::Aws),
        implementation: "queue::s3::S3Backend",
        summary: "Shared Amazon S3 queue and object store.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Storage(StorageAdapter::S3),
        config: S3_CONFIG,
    },
    CapabilityVariant {
        id: StorageAdapter::Local.id(),
        aliases: &[],
        provider: Some(ProviderId::Local),
        implementation: "queue::local_file::LocalBackend",
        summary: "Device-local filesystem store for one-host operation.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Storage(StorageAdapter::Local),
        config: LOCAL_STORAGE_CONFIG,
    },
    CapabilityVariant {
        id: StorageAdapter::StadoObject.id(),
        aliases: &["stado-object"],
        provider: Some(ProviderId::Stado),
        implementation: "queue::stado_object::StadoObjectBackend",
        summary: "Shared provider-neutral queue through the authenticated Stado object API.",
        configurable: true,
        constructible: true,
        adapter: RuntimeAdapter::Storage(StorageAdapter::StadoObject),
        config: STADO_OBJECT_STORAGE_CONFIG,
    },
];

pub(in crate::capabilities::registry) const EXECUTION: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: ProviderId::Local.as_str(),
        aliases: ProviderId::Local.aliases(),
        provider: Some(ProviderId::Local),
        implementation: "providers::local::agent",
        summary: "Long-lived workstation or server agent.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::Local),
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Gcp.as_str(),
        aliases: ProviderId::Gcp.aliases(),
        provider: Some(ProviderId::Gcp),
        implementation: "providers::local::agent + monitor::reap + providers::gcp",
        summary: "Ephemeral agent running inside a GCE VM.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::Gcp),
        config: GCP_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Azure.as_str(),
        aliases: ProviderId::Azure.aliases(),
        provider: Some(ProviderId::Azure),
        implementation: "providers::local::agent + monitor::reap + providers::azure",
        summary: "Ephemeral agent running inside an Azure VM.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::Azure),
        config: AZURE_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Aws.as_str(),
        aliases: ProviderId::Aws.aliases(),
        provider: Some(ProviderId::Aws),
        implementation: "providers::local::agent + monitor::reap + providers::aws",
        summary: "Ephemeral agent running inside an EC2 VM.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::Aws),
        config: AWS_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Box.as_str(),
        aliases: ProviderId::Box.aliases(),
        provider: Some(ProviderId::Box),
        implementation: "providers::local::agent + providers::box",
        summary: "Agent bootstrapped on an externally managed box.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::Box),
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Vast.as_str(),
        aliases: ProviderId::Vast.aliases(),
        provider: Some(ProviderId::Vast),
        implementation: "providers::local::agent + providers::vast",
        summary: "Agent on a Vast.ai-listed host.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Execution(ExecutionAdapter::Vast),
        config: &[],
    },
    gpu_cloud_execution(GpuCloudVendor::Crusoe),
    gpu_cloud_execution(GpuCloudVendor::Cudo),
    gpu_cloud_execution(GpuCloudVendor::Hyperstack),
    gpu_cloud_execution(GpuCloudVendor::Lambda),
    gpu_cloud_execution(GpuCloudVendor::Latitude),
    gpu_cloud_execution(GpuCloudVendor::Nebius),
    gpu_cloud_execution(GpuCloudVendor::Oblivus),
    gpu_cloud_execution(GpuCloudVendor::Oracle),
    gpu_cloud_execution(GpuCloudVendor::Runpod),
    gpu_cloud_execution(GpuCloudVendor::Salad),
    gpu_cloud_execution(GpuCloudVendor::Scaleway),
    gpu_cloud_execution(GpuCloudVendor::VoltagePark),
    gpu_cloud_execution(GpuCloudVendor::Vultr),
];

pub(in crate::capabilities::registry) const SCHEDULING: &[CapabilityVariant] =
    &[CapabilityVariant {
        id: "central-makespan",
        aliases: &[],
        provider: Some(ProviderId::Stado),
        implementation: "scheduler::scheduler + scheduler::makespan",
        summary: "Provider-neutral queue assignment and makespan minimization.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    }];
