//! Deployment, host target and dependency variants.

use crate::capabilities::catalog::ProviderId;
use crate::capabilities::config::variants::{
    AWS_COMPUTE_CONFIG, AZURE_COMPUTE_CONFIG, GCP_COMPUTE_CONFIG, LOCAL_STORAGE_CONFIG,
};
use crate::capabilities::registry::CapabilityVariant;
use crate::capabilities::runtime::{DependencyAdapter, RuntimeAdapter};

pub(in crate::capabilities::registry) const DEPLOYMENT: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: "launchd",
        aliases: &[],
        provider: Some(ProviderId::Macos),
        implementation: "deploy::service",
        summary: "macOS launchd service installation and lifecycle.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "systemd",
        aliases: &[],
        provider: Some(ProviderId::Linux),
        implementation: "deploy::service",
        summary: "Linux systemd service installation and lifecycle.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "cloud-function",
        aliases: &[],
        provider: Some(ProviderId::Gcp),
        implementation: "control_plane::cloud",
        summary: "Interval-driven cloud control-plane tick.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: GCP_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: "vm-bootstrap",
        aliases: &[],
        provider: Some(ProviderId::MultiCloud),
        implementation: "deploy::bootstrap + data/templates",
        summary: "GCP, AWS and Azure agent VM bootstrap templates.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "https-release",
        aliases: &[],
        provider: Some(ProviderId::ProviderNeutral),
        implementation: "self_update",
        summary: "Signed binary release channel served by an HTTPS origin.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
];

pub(in crate::capabilities::registry) const HOST_TARGET: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: ProviderId::Gcp.as_str(),
        aliases: ProviderId::Gcp.aliases(),
        provider: Some(ProviderId::Gcp),
        implementation: "targets::ComputeTarget",
        summary: "GCP dispatcher target recorded in the host registry.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: GCP_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Local.as_str(),
        aliases: ProviderId::Local.aliases(),
        provider: Some(ProviderId::Local),
        implementation: "targets::ComputeTarget",
        summary: "Physical or SSH-reachable host recorded in the registry.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Vast.as_str(),
        aliases: ProviderId::Vast.aliases(),
        provider: Some(ProviderId::Vast),
        implementation: "targets::ComputeTarget",
        summary: "Vast.ai dispatcher pool recorded in the registry.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
];

pub(in crate::capabilities::registry) const DEPENDENCY: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: ProviderId::Gcp.as_str(),
        aliases: ProviderId::Gcp.aliases(),
        provider: Some(ProviderId::Gcp),
        implementation: "cli::blast_radius",
        summary: "Inspect GCP-owned storage and release dependencies.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Dependency(DependencyAdapter::Gcp),
        config: GCP_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Azure.as_str(),
        aliases: ProviderId::Azure.aliases(),
        provider: Some(ProviderId::Azure),
        implementation: "cli::blast_radius",
        summary: "Inspect Azure-owned storage and release dependencies.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Dependency(DependencyAdapter::Azure),
        config: AZURE_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Aws.as_str(),
        aliases: ProviderId::Aws.aliases(),
        provider: Some(ProviderId::Aws),
        implementation: "cli::blast_radius",
        summary: "Inspect AWS-owned storage and release dependencies.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Dependency(DependencyAdapter::Aws),
        config: AWS_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: ProviderId::Local.as_str(),
        aliases: ProviderId::Local.aliases(),
        provider: Some(ProviderId::Local),
        implementation: "cli::blast_radius",
        summary: "Inspect device-local storage and release dependencies.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::Dependency(DependencyAdapter::Local),
        config: LOCAL_STORAGE_CONFIG,
    },
];
