//! Authentication, secrets and alert variants.

use crate::capabilities::catalog::ProviderId;
use crate::capabilities::config::variants::{
    AWS_COMPUTE_CONFIG, AZURE_COMPUTE_CONFIG, GCP_COMPUTE_CONFIG,
};
use crate::capabilities::registry::CapabilityVariant;
use crate::capabilities::runtime::RuntimeAdapter;

pub(in crate::capabilities::registry) const AUTHENTICATION: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: "object-token",
        aliases: &[],
        provider: Some(ProviderId::Skarbiec),
        implementation: "dashboard::authorize_object",
        summary: "Namespace and key-prefix scoped product bearers resolved from mapped <namespace>-object-api/token items.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "release-publisher-token",
        aliases: &[],
        provider: Some(ProviderId::Skarbiec),
        implementation: "dashboard::authorize_release",
        summary: "Product-prefix scoped immutable release publisher bearers resolved from mapped <product>-release-publisher/token items.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "machine-token",
        aliases: &[],
        provider: Some(ProviderId::Skarbiec),
        implementation: "dashboard::authenticate_machine_client",
        summary: "Machine submit/status/cancel bearer stored as stado-machine-api/token.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "service-token",
        aliases: &[],
        provider: Some(ProviderId::Skarbiec),
        implementation: "dashboard::authorize_service",
        summary: "Exact service/action bearer resolved from service_api.deployers.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "host-health-token",
        aliases: &[],
        provider: Some(ProviderId::Skarbiec),
        implementation: "dashboard::authorize_host_health + cli::host::publish_beacon",
        summary: "Route-scoped host beacon publisher bearer resolved from stado-host-health-api/token.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
];

pub(in crate::capabilities::registry) const SECRETS: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: ProviderId::Skarbiec.as_str(),
        aliases: ProviderId::Skarbiec.aliases(),
        provider: Some(ProviderId::Skarbiec),
        implementation: "skarbiec::Client",
        summary: "Scoped application and workload-secret retrieval.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "gcp-adc",
        aliases: &[],
        provider: Some(ProviderId::Gcp),
        implementation: "skarbiec::gcp_provider",
        summary: "GCP Application Default Credentials and workload identity.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: GCP_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: "aws-credential-chain",
        aliases: &[],
        provider: Some(ProviderId::Aws),
        implementation: "providers::aws::sdk_config",
        summary: "AWS credential chain, IMDS and the scoped Skarbiec identity.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: AWS_COMPUTE_CONFIG,
    },
    CapabilityVariant {
        id: "azure-managed-identity",
        aliases: &[],
        provider: Some(ProviderId::Azure),
        implementation: "azure_token",
        summary: "Azure managed identity and encrypted operator session.",
        configurable: false,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: AZURE_COMPUTE_CONFIG,
    },
];

pub(in crate::capabilities::registry) const ALERTS: &[CapabilityVariant] = &[
    CapabilityVariant {
        id: ProviderId::Slack.as_str(),
        aliases: ProviderId::Slack.aliases(),
        provider: Some(ProviderId::Slack),
        implementation: "monitor::alerts",
        summary: "Slack incoming-webhook delivery.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Telegram.as_str(),
        aliases: ProviderId::Telegram.aliases(),
        provider: Some(ProviderId::Telegram),
        implementation: "monitor::alerts",
        summary: "Telegram Bot API delivery.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Sendgrid.as_str(),
        aliases: ProviderId::Sendgrid.aliases(),
        provider: Some(ProviderId::Sendgrid),
        implementation: "monitor::alerts",
        summary: "SendGrid email delivery.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Resend.as_str(),
        aliases: ProviderId::Resend.aliases(),
        provider: Some(ProviderId::Resend),
        implementation: "monitor::alerts",
        summary: "Resend email delivery.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: ProviderId::Most.as_str(),
        aliases: ProviderId::Most.aliases(),
        provider: Some(ProviderId::Most),
        implementation: "monitor::alerts",
        summary: "Twilio SMS delivery through the Most integration provider.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: &[],
    },
    CapabilityVariant {
        id: "gcp-pubsub",
        aliases: &[],
        provider: Some(ProviderId::Gcp),
        implementation: "monitor::alerts",
        summary: "GCP Pub/Sub alert publication.",
        configurable: true,
        constructible: false,
        adapter: RuntimeAdapter::None,
        config: GCP_COMPUTE_CONFIG,
    },
];
