//! The permission and role contract the probes assert: the payload of the
//! `caller_permissions` probe and the yardstick its detail is measured against.

pub(in crate::providers::gcp::inventory) const REQUIRED_PERMISSIONS: &[&str] = &[
    "artifactregistry.repositories.get",
    "bigquery.datasets.get",
    "bigquery.jobs.create",
    "bigquery.tables.get",
    "bigquery.tables.getData",
    "cloudscheduler.jobs.get",
    "cloudscheduler.jobs.list",
    "cloudfunctions.functions.get",
    "cloudfunctions.functions.list",
    "cloudbuild.builds.list",
    "compute.addresses.list",
    "compute.disks.create",
    "compute.disks.delete",
    "compute.disks.list",
    "compute.firewalls.list",
    "compute.images.get",
    "compute.images.useReadOnly",
    "compute.instanceGroupManagers.list",
    "compute.instances.create",
    "compute.instances.delete",
    "compute.instances.get",
    "compute.instances.setMetadata",
    "compute.instances.list",
    "compute.networks.get",
    "compute.regions.get",
    "compute.reservations.list",
    "compute.snapshots.list",
    "compute.zoneOperations.get",
    "iam.serviceAccounts.actAs",
    "iam.serviceAccounts.get",
    "iam.serviceAccounts.list",
    "pubsub.topics.get",
    "pubsub.topics.publish",
    "resourcemanager.projects.get",
    "resourcemanager.projects.getIamPolicy",
    "run.revisions.list",
    "run.services.get",
    "run.services.getIamPolicy",
    "storage.buckets.get",
    "storage.buckets.list",
    "storage.objects.get",
    "storage.objects.create",
    "storage.objects.delete",
    "storage.objects.list",
    "storage.objects.update",
];

pub(in crate::providers::gcp::inventory) const REQUIRED_RUNTIME_ROLES: &[&str] = &[
    "roles/bigquery.dataViewer",
    "roles/bigquery.jobUser",
    "roles/compute.admin",
    "roles/pubsub.publisher",
    "roles/storage.admin",
];
