//! Configuration facets: one catalogued key, the control plane's register of
//! the keys it reads itself, the declarations a reader honours, and the
//! adapter-owned keys a runtime variant carries.

mod control;
mod declaration;
mod field;
pub(super) mod variants;

pub use control::{
    SkarbiecBinding, AGENT_SKARBIEC, AGENT_SKARBIEC_ITEMS_CONFIG,
    AGENT_SKARBIEC_SECRET_FIELDS_CONFIG, ALERT_CHANNELS_CONFIG, ALERT_EMAIL_FROM_CONFIG,
    ALERT_EMAIL_TO_CONFIG, ALERT_RESEND_FIELD_CONFIG, ALERT_RESEND_ITEM_CONFIG, API_URL_CONFIG,
    BACKEND_MESSAGING_SKARBIEC_ITEMS_CONFIG, CONTROL_CONFIG, CREDENTIALS_STORE_CONFIG,
    DASHBOARD_BIND_CONFIG, DASHBOARD_PORT_CONFIG, DATABASE_API_DATABASES_CONFIG,
    DEPLOYMENT_ID_CONFIG, DISABLED_PROVIDERS_CONFIG, INTEGRATION_CLIENTS_CONFIG,
    INTEGRATION_PROVIDERS_CONFIG, MACHINE_API_CLIENTS_CONFIG, OBJECT_API_NAMESPACES_CONFIG,
    PROVIDERS_CONFIG, RATE_LIMIT_CLIENTS_CONFIG, RELEASE_AGENT_RUNTIME_BUNDLE_SHA256_CONFIG,
    RELEASE_AGENT_RUNTIME_BUNDLE_URI_CONFIG, RELEASE_API_PUBLISHERS_CONFIG,
    RELEASE_PLATFORM_CONFIG, RELEASE_SIGNING_KEY_ID_CONFIG, RELEASE_SIGNING_KEY_ITEM_CONFIG,
    RELEASE_VERSION_CONFIG, SECRETS_SKARBIEC, SERVICE_API_DEPLOYERS_CONFIG,
    SKARBIEC_VAULT_FILE_CONFIG, STORAGE_BACKEND_CONFIG, WEB_API_PRODUCTS_CONFIG,
};
pub use declaration::{
    declared_field, Consumer, DeclarationSurface, DeclaredField, SiblingCondition, DECLARED_FIELDS,
};
pub use field::{ConfigField, ConfigValueKind};
