//! The launcher the managed unit executes, generated rather than carried by
//! the product.

use crate::cli::web::builds::contract::package::kind::Kind;
use crate::cli::web::builds::payload::STATIC_SERVER;

/// The launcher the managed unit executes, generated rather than carried by
/// the product so all thirty-four web products start the same way.
///
/// It resolves its own root from `$0` because the tarball is extracted under
/// `$HOME/.stado/services/<name>/current` on whichever host runs the unit, and
/// a path baked in at build time would be the builder's path, not that one.
/// It sources `WEB_ENV_FILE` because that is where `stado service secret-sync`
/// puts a Skarbiec value: an owner-only file, never the unit document, since a
/// secret written into a launchd plist or a systemd unit is a secret committed
/// to the registry. Nothing else in the run path would read it, and a secret
/// delivered but never read is an outage that reports success.
///
/// A static site gets the same script with one line different: `node` on the
/// server this build staged, instead of `npm run start` on a script the
/// product does not have. Everything the unit relies on — the launcher's
/// path, the `PORT` contract, the environment file, loopback only — is
/// identical, which is why `stado web deploy` does not know the difference.
pub(super) fn launcher(kind: Kind, site_root: &str) -> String {
    let exec = match kind {
        Kind::Server => "exec npm run start -- --port \"$port\" --hostname 127.0.0.1".to_string(),
        // The site root travels as an argument rather than being resolved by
        // the server itself: the build is the only thing that knows which
        // directory the recipe declared, and a server that guessed would
        // serve whatever happened to be extracted beside it.
        Kind::Static => format!(
            "exec node \"$root/{STATIC_SERVER}\" --root \"$root/{site_root}\" --port \"$port\" --hostname 127.0.0.1"
        ),
    };
    let what = match kind {
        Kind::Server => "Starts this product's own `start` script on",
        Kind::Static => "Serves this product's static site on",
    };
    // The script carries its own reasoning, because whoever reads it next will
    // be reading it inside an install root on a fleet host, with none of this
    // module in front of them.
    format!(
        r#"#!/bin/sh
# Generated by `stado web build`. {what}
# the loopback port the managed unit was declared with.
#
# --hostname 127.0.0.1 is load-bearing, not a default. The public edge is what
# holds 443 and terminates TLS for this product's hostname; a unit bound to
# every interface would be a second entrance to the same application, reachable
# across the tailnet with nothing in front of it and no certificate involved.
# Loopback only, so the edge is the only way in.
set -eu

# The install root is wherever the release was extracted, so it is resolved
# from $0 rather than written in at build time.
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"

# The port is checked, and captured, before anything else can define one. The
# unit passes the port this product was declared with; a value sourced from the
# environment file must not be able to answer for it, or a product could quietly
# listen somewhere the edge does not forward to.
if [ -z "${{PORT:-}}" ]; then
  echo "start-web: PORT is unset; the managed unit must pass the loopback port this product was declared with" >&2
  exit 1
fi
port=$PORT

# The unit's secrets arrive in an owner-only file whose absolute path the unit
# passes as WEB_ENV_FILE, written one variable at a time by
# `stado service secret-sync`. `set -a` is what exports the assignments into
# the server's environment; a plain `.` would leave them as shell variables the
# server never sees, and every delivered credential would be dead text.
if [ -n "${{WEB_ENV_FILE:-}}" ] && [ -f "$WEB_ENV_FILE" ]; then
  set -a
  . "$WEB_ENV_FILE"
  set +a
fi

{exec}
"#
    )
}

/// The old zero-argument launcher, kept as the server-product spelling so the
/// tests that fix its contract read the way they did.
pub(super) fn server_launcher() -> String {
    launcher(Kind::Server, "")
}
