//! The static file server that travels inside the artifact.

/// The static file server that travels inside the artifact.
///
/// It is generated here, in the tarball, for the same reason the launcher is:
/// the unit runs from the artifact and installs nothing at deploy time. A
/// global `serve` would be a dependency of the host rather than of the
/// release, and `npx serve` would fetch from the npm registry the first time
/// a unit started — a network call in the run path, resolving a version
/// nobody pinned, on a host whose whole point is that the bytes it runs are
/// the bytes someone published. Node's own `http` module is enough.
///
/// The routing is what Vercel did for these six sites: an exact file, then
/// `<path>.html`, then `<path>/index.html`. That is `cleanUrls`, which
/// `jeden`'s `vercel.json` sets explicitly and the others rely on for
/// `/docs`, and it is the difference between a migrated site whose links work
/// and one that 404s everywhere but the front page.
pub(super) fn static_server() -> &'static str {
    r#"// Generated by `stado web build`. The static server a Stado-hosted site
// runs from inside its own release artifact.
//
// Nothing is installed at deploy time and nothing is fetched at run time, so
// this uses only node:http, node:fs and node:path. `npx serve` would resolve
// and download a package on first start; a host that must run exactly the
// bytes that were published cannot have a package manager in its run path.
import { createServer } from "node:http";
import { createReadStream, promises as fs } from "node:fs";
import { extname, join, normalize, resolve, sep } from "node:path";

function argument(name, otherwise) {
  const at = process.argv.indexOf(`--${name}`);
  return at !== -1 && process.argv[at + 1] !== undefined ? process.argv[at + 1] : otherwise;
}

const root = resolve(argument("root", "."));
const port = Number(argument("port", process.env.PORT ?? ""));
const hostname = argument("hostname", "127.0.0.1");
if (!Number.isInteger(port) || port <= 0) {
  console.error("serve-static: --port must be the loopback port this unit was declared with");
  process.exit(1);
}

// Content types are a fixed table rather than a lookup in a dependency. A
// missing one is served as octet-stream, which a browser downloads instead of
// rendering — visible, and never a wrong interpretation of the bytes.
const TYPES = new Map(Object.entries({
  ".html": "text/html; charset=utf-8",
  ".htm": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".map": "application/json; charset=utf-8",
  ".pdf": "application/pdf",
  ".webmanifest": "application/manifest+json",
}));

async function file(candidate) {
  // The resolved path is confined to the site root before anything is opened.
  // A request path is attacker-controlled, and `/../../etc/passwd` decoded is
  // an ordinary-looking one.
  const inside = candidate === root || candidate.startsWith(root + sep);
  if (!inside) return null;
  try {
    const found = await fs.stat(candidate);
    return found.isFile() ? { path: candidate, size: found.size } : null;
  } catch {
    return null;
  }
}

// The same resolution order Vercel's `cleanUrls` gives these sites: the exact
// file, then the same path with .html, then a directory's index.html. A site
// whose links are /docs rather than /docs.html depends on the second one.
async function resolveRequest(pathname) {
  const relative = normalize(decodeURIComponent(pathname)).replace(/^(\.\.[/\\])+/, "");
  const candidate = resolve(join(root, relative));
  const direct = await file(candidate);
  if (direct) return direct;
  if (!pathname.endsWith("/")) {
    const asHtml = await file(`${candidate}.html`);
    if (asHtml) return asHtml;
  }
  return await file(join(candidate, "index.html"));
}

const server = createServer(async (request, response) => {
  // A static site answers reads. Anything else is refused by method rather
  // than falling through to a 404, which would say the path is wrong when the
  // verb is.
  if (request.method !== "GET" && request.method !== "HEAD") {
    response.writeHead(405, { "content-type": "text/plain; charset=utf-8", allow: "GET, HEAD" });
    response.end("method not allowed\n");
    return;
  }
  const pathname = new URL(request.url, `http://${hostname}`).pathname;
  const found = await resolveRequest(pathname);
  if (!found) {
    const custom = await file(join(root, "404.html"));
    const status = 404;
    if (custom && request.method === "GET") {
      response.writeHead(status, { "content-type": "text/html; charset=utf-8", "content-length": custom.size });
      createReadStream(custom.path).pipe(response);
      return;
    }
    response.writeHead(status, { "content-type": "text/plain; charset=utf-8" });
    response.end(request.method === "HEAD" ? undefined : "not found\n");
    return;
  }
  response.writeHead(200, {
    "content-type": TYPES.get(extname(found.path).toLowerCase()) ?? "application/octet-stream",
    "content-length": found.size,
    "x-content-type-options": "nosniff",
  });
  if (request.method === "HEAD") {
    response.end();
    return;
  }
  createReadStream(found.path).pipe(response);
});

server.listen(port, hostname, () => {
  console.log(`serve-static: ${root} on http://${hostname}:${port}`);
});
"#
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_static_server_fetches_nothing_and_stays_inside_the_site() {
        let server = static_server();
        // A unit must run the bytes that were published. `npx` or a global
        // install would resolve and download a package the first time a unit
        // started, on a host whose whole point is that it does not. The
        // server's own comments say that, so the check is over its code: a
        // comment mentioning `npx` is the reasoning, an executable line
        // mentioning it is the defect.
        let code: String = server
            .lines()
            .filter(|line| !line.trim_start().starts_with("//"))
            .collect::<Vec<&str>>()
            .join("\n");
        assert!(!code.contains("npx"), "{code}");
        assert!(!code.contains("require("));
        for module in ["node:http", "node:fs", "node:path"] {
            assert!(server.contains(module), "{module} must be imported");
        }
        // Every import is a Node builtin: an artifact that needed a package
        // would need node_modules, which a static site does not stage.
        for line in server.lines().filter(|line| line.starts_with("import ")) {
            assert!(line.contains("\"node:"), "{line} imports something else");
        }
        // A request path is attacker-controlled, so the resolved path is
        // confined to the site root before anything is opened.
        assert!(server.contains("candidate.startsWith(root + sep)"));
        // Loopback is the default here too, so a server started by hand
        // cannot accidentally answer the tailnet.
        assert!(server.contains("argument(\"hostname\", \"127.0.0.1\")"));
        // The clean-URL order these six sites were served with.
        assert!(server.contains("`${candidate}.html`"));
        assert!(server.contains("join(candidate, \"index.html\")"));
    }
}
