#!/usr/bin/env bash
# Refuse a release whose declared version disagrees with what it did to the public
# contract of `stado`. That contract is the command list the binary advertises: adding
# a command is a capability, removing one breaks every script that invoked it.
#
# The rule itself has one home for the whole fleet and is not copied here:
# https://github.com/lbartoszcze/AutoVersion. This script supplies only the three
# things this repository alone knows — the surface of the artifact about to be
# published, the version that artifact declares, and which release channel it is
# published to.
#
# Run by .github/workflows/deploy.yml in front of the first `storage put`. Release
# objects are create-only, so a wrong version is not a mistake anyone can correct
# afterwards; the only useful place for this check is ahead of the publish it guards.
#
# Usage:
#   scripts/version_check.sh <candidate-surface.json>
# Environment:
#   AUTOVERSION  the shared rule's entry point
#   STADO_BIN    stado used to read the channel
#   BASELINE     baseline generated from verified release bytes (required)
#   MANIFEST     the crate that declares version (default: stado-rs/Cargo.toml)

set -euo pipefail
script_dir="$(cd "$(dirname "$0")" && pwd)"

candidate="${1:?usage: scripts/version_check.sh <candidate-surface.json>}"
baseline="${BASELINE:?set BASELINE to the document generated by scripts/baseline.py --output}"
manifest="${MANIFEST:-stado-rs/Cargo.toml}"
autoversion="${AUTOVERSION:?set AUTOVERSION to the pinned rule}"
stado_bin="${STADO_BIN:?set STADO_BIN to the channel-aware stado binary}"

test -r "$candidate"
test -r "$baseline"
test -r "$manifest"
test -x "$stado_bin"

# Read the declared version exactly the way deploy.yml reads it, so the gate and the
# publish can never disagree about what is being released.
version_line="$(sed -n '/^version = /p' "$manifest")"
declared="${version_line#*\"}"
declared="${declared%%\"*}"
released="$(jq -r .version "$baseline")"
test -n "$declared"
test -n "$released"
echo "declared version: $declared"
echo "baseline version: $released"

verdict="$("$autoversion" decide \
  --current "$released" \
  --published-surface "$baseline" \
  --candidate-surface "$candidate" \
  --json)"
echo "$verdict"

change="$(printf '%s' "$verdict" | jq -r .change)"
required="$(printf '%s' "$verdict" | jq -r .next)"
test -n "$change"
test -n "$required"

if [ "$declared" = "$released" ]; then
  if [ "$change" != internal ]; then
    echo "::error::The advertised command surface changed ($change), but" \
      "$manifest still declares the baseline version $released." \
      "The next version must be $required."
    false
  fi
  echo "The surface is unchanged, so the declared version may stay $released."
elif ! "$script_dir/semver_at_least.py" "$declared" "$required"; then
  echo "::error::$manifest declares $declared, but a $change change to" \
    "$released requires at least $required."
  false
else
  echo "Declared version $declared satisfies the $change change (minimum $required)."
fi

# scripts/baseline.py writes the exact manifest URI it read and verified. A
# hand-written phrase, tag, or guessed coordinate has no accepted spelling.
marker="$(jq -r '.source | split(" ") | first' "$baseline")"
echo "baseline marker: $marker"
case "$marker" in
  stado://releases/stado/*/release-manifest-*.json) ;;
  *)
    echo "::error::unknown baseline marker in $baseline: $marker." \
      "Generate it from the channel: python3 scripts/baseline.py --best --stado STADO --output BASELINE"
    false
    ;;
esac

# What the channel itself says about the exact object the baseline names.
#
# This used to list `releases` through the object API and search the result. That
# route does not exist on the release channel and never did: releases are published
# and served by their own route, which answers a served object with a redirect to
# where the bytes live. The listing therefore returned a 404 on every run, and under
# `set -e` the gate died before judging anything -- a gate that cannot say yes is as
# useless as one that cannot say no.
#
# `storage stat` on a full stado:// URI asks the channel and names one of three
# states, where a listing had only silence. Only a stated present or absent counts.
# Anything else -- unreachable, an empty field, a state this script does not know --
# is an answer nobody gave, and refusing is the direction that cannot certify a lie.
# Its stderr is deliberately not swallowed: when the channel fails to answer, the
# reason belongs in the log next to the refusal it caused.
channel_state() {
  "$stado_bin" storage stat "$1" --json | jq -r '.state // ""' || true
}

state="$(channel_state "$marker")"
case "$state" in
  present) ;;
  absent)
    echo "::error::$baseline names $marker, which the release channel no longer serves."
    false
    ;;
  *)
    echo "::error::the release channel did not testify about $marker (state" \
      "'${state:-none}'), so the generated baseline cannot be trusted."
    false
    ;;
esac
echo "The channel serves $marker, as the generated baseline records."

# The generator must independently select the same version now. This catches a
# newer complete release appearing between baseline generation and the verdict.
have="stado:$released"
# Into a file, with the status tested on its own line. `set -e` does reach a bare
# assignment from a command substitution, but it stops reaching the moment a pipeline
# appears inside one, and this line is one edit away from growing a `| tail` -- so the
# status is tested where it cannot be discarded. Then both identities are asserted
# non-empty BEFORE they are compared: an identity that read empty must be reported as
# an identity that read empty, not as an artifact named "" superseding this baseline,
# and if both sides ever read empty the comparison would pass vacuously.
scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT
if ! python3 scripts/baseline.py --best --stado "$stado_bin" > "$scratch/best"; then
  echo "::error::the baseline generator could not establish the best reachable" \
    "artifact, so whether this baseline is superseded is unproven." \
    "Refusing rather than assuming it is current."
  false
fi
best="$(cat "$scratch/best")"
if [ -z "$best" ] || [ -z "$have" ]; then
  echo "::error::an artifact identity read empty (best '$best', baseline '$have')," \
    "so this comparison would prove nothing."
  false
fi
if [ "$best" != "$have" ]; then
  echo "::error::the generated baseline is $have, but $best is reachable now." \
    "Generate the baseline again from one channel snapshot."
  false
fi
echo "$have is still the best artifact available."
