#!/usr/bin/env bash
# Prove that scripts/version_check.sh actually refuses. A gate nobody has watched say
# no is indistinguishable from a gate that always says yes, and this one guards
# create-only release objects, so the refusals are the part worth checking.
#
# Five cases, run against a baseline generated from verified channel bytes:
#   1 surface untouched                     -> internal, passes
#   2 one advertised command removed        -> breaking, refuses
#   3 one advertised command added          -> additive, refuses
#   4 "source" is prose, not a manifest URI -> refuses
#   5 baseline names an object the channel does not serve -> refuses
#
# Cases mutate copies under a temporary directory. The repository is never
# written to.
#
# Usage:
#   BASELINE=/path/generated.json scripts/version_check_proof.sh [stado-binary]
# Environment:
#   BASELINE     document generated by scripts/baseline.py --output (required)
#   AUTOVERSION  the shared rule's entry point
#   STADO_BIN    stado used to read the channel
set -uo pipefail

repository="$(cd "$(dirname "$0")/.." && pwd)" || exit
cd "$repository" || exit

binary="${1:-stado-rs/target/release/stado}"
export BASELINE="${BASELINE:?set BASELINE to a channel-generated document}"
export AUTOVERSION="${AUTOVERSION:?set AUTOVERSION to the pinned rule}"
export STADO_BIN="${STADO_BIN:?set STADO_BIN to the channel-aware stado binary}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
failures=""

# check_case <name> <pass|refuse> <baseline> <candidate>
check_case() {
  local name="$1" expected="$2" baseline="$3" candidate="$4" observed
  echo
  echo "### $name (expect $expected)"
  if BASELINE="$baseline" scripts/version_check.sh "$candidate"; then
    observed=pass
  else
    observed=refuse
  fi
  if [ "$observed" = "$expected" ]; then
    echo "OK: $name -> $observed"
  else
    echo "FAIL: $name -> $observed, expected $expected"
    failures="${failures}x"
  fi
}

python3 scripts/surface.py --binary "$binary" > "$work/candidate.json" || exit
removed="$(jq -r '.surface | last' "$work/candidate.json")"
echo "candidate surface: $(jq -c '.surface | length' "$work/candidate.json") commands"
jq -c .surface "$work/candidate.json"

jq --arg gone "$removed" '{surface: (.surface | map(select(. != $gone)))}' \
  "$work/candidate.json" > "$work/removed.json"
jq '{surface: ((.surface + ["teleport"]) | sort)}' \
  "$work/candidate.json" > "$work/added.json"
jq '.source = "handwritten by someone in a hurry"' "$BASELINE" \
  > "$work/prose.json"
jq '.source = "stado://releases/stado/9.9.9/nowhere-noarch/release-manifest-nowhere-noarch.json published from 0000000000000000000000000000000000000000"' \
  "$BASELINE" > "$work/absent-object.json"

# Case 3 needs a baseline that already carries this tree's surface at the version this
# tree declares. Compared against the published baseline instead, it proves nothing:
# this tree is normally already additive over what the channel serves, so one more
# command changes neither the class of the change nor the version it demands, and the
# case passes for a reason that has nothing to do with the command it added. The
# marker is left untouched, because the gate uses it only to confirm the channel still
# serves the object the baseline names, which stays true.
version_line="$(sed -n '/^version = /p' stado-rs/Cargo.toml)"
declared="${version_line#*\"}"
declared="${declared%%\"*}"
jq --arg declared "$declared" --slurpfile candidate "$work/candidate.json" \
  '.version = $declared | .surface = $candidate[0].surface' "$BASELINE" \
  > "$work/current.json"

check_case "surface untouched" pass "$BASELINE" "$work/candidate.json"
check_case "removed $removed" refuse "$BASELINE" "$work/removed.json"
check_case "added teleport" refuse "$work/current.json" "$work/added.json"
check_case "prose baseline source" refuse "$work/prose.json" "$work/candidate.json"
check_case "baseline claims absent object" refuse "$work/absent-object.json" \
  "$work/candidate.json"

echo
if [ -n "$failures" ]; then
  echo "the gate did not behave as specified"
  false
else
  echo "every case behaved as specified"
fi
