//! The whole configuration file: rendered from the declarations, and read
//! back out of what the edge holds.

use crate::config::{self, WebApiEdge};

#[cfg(test)]
mod corpus;
#[cfg(test)]
mod fixtures;
#[cfg(test)]
mod mounts;
#[cfg(test)]
mod rendering;

/// The whole edge configuration, rendered from the declarations.
///
/// Pure, and the only thing that produces a Caddyfile for this fleet. The
/// global block carries the ACME contact so Let's Encrypt has somewhere to
/// send an expiry warning; every site block is one hostname and the one
/// directive that answers it — `reverse_proxy` for a product with a unit,
/// `redir` for a product that is only a redirect — and Caddy obtains and
/// renews that hostname's certificate from the site address alone. Nothing
/// declares a log destination: the proxy runs as a managed unit, so its
/// output is already where `stado service logs` reads it, and a second log
/// file on the host would be one nothing rotates.
pub(in crate::cli::web) fn caddyfile(
    edge: &WebApiEdge,
    routes: &[(String, Vec<String>)],
) -> String {
    let mut text = String::with_capacity(320 + routes.len() * 96);
    text.push_str(
        "# Generated by `stado web edge`; the source of truth is web_api.products in\n\
         # Stado's configuration. Every reconcile replaces this whole file, so an edit\n\
         # made on this host survives exactly until the next `stado web route`.\n",
    );
    text.push_str("{\n\temail ");
    text.push_str(edge.contact());
    text.push_str("\n}\n");
    if routes.is_empty() {
        text.push_str(
            "\n# No declared web product names this edge, so it terminates nothing and\n\
             # orders no certificate.\n",
        );
        return text;
    }
    for (hostname, block) in routes {
        text.push('\n');
        text.push_str(hostname);
        text.push_str(" {\n");
        // In order: every mount's `handle_path`, then the directive that
        // answers the rest. Caddy takes the first matching route in a block,
        // so this order is what makes `/docs` the mount's and everything else
        // the owner's.
        for directive in block {
            text.push('\t');
            text.push_str(directive);
            text.push('\n');
        }
        text.push_str("}\n");
    }
    text
}

/// The hostnames one Caddyfile terminates, read back out of it.
///
/// The reconcile's other half: [`caddyfile`] says what the edge must serve,
/// this says what the file on the edge actually does. A site block opens at
/// column zero and ends the line with `{`; the global options block opens with
/// a bare `{`, and every directive inside a block is indented, so neither can
/// be mistaken for a site address.
pub(in crate::cli::web) fn terminated_hostnames(text: &str) -> Vec<String> {
    let mut hostnames = Vec::new();
    for line in text.lines() {
        if line.starts_with(char::is_whitespace) || line.starts_with('#') {
            continue;
        }
        let Some(addresses) = line.trim_end().strip_suffix('{') else {
            continue;
        };
        for token in
            addresses.split(|character: char| character == ',' || character.is_whitespace())
        {
            if config::is_public_hostname(token) {
                hostnames.push(token.to_string());
            }
        }
    }
    hostnames.sort();
    hostnames.dedup();
    hostnames
}
