//! Processes that really run on this machine out of a managed run directory,
//! and the state each one leaves behind.

use std::io::Write;
use std::process::Stdio;
use std::time::{Duration, Instant};

use serde_json::Value;

use crate::fixture::{executable, receipt, said, stderr, Fixture, TARGET};

/// How long a case waits for a program it started to reach the state it is
/// waiting for. Generous: the machine may be building for another area.
const READY_TIMEOUT: Duration = Duration::from_secs(30);

#[test]
fn an_attached_program_runs_here_consuming_stdin_and_leaving_its_own_output() {
    let fixture = Fixture::new();
    let run = fixture.run("attached-stdio");
    let program = run.join("worker");
    let receipt_path = run.join("worker.out");
    executable(
        &program,
        &format!(
            "#!/bin/sh\nIFS= read -r line\nprintf 'worker:%s\\n' \"$line\"\nprintf '%s' \"$line\" > {}\nprintf 'worker diagnostic\\n' >&2\n",
            receipt_path.display()
        ),
    );

    let mut child = fixture
        .command(&[
            "host",
            "run-attached",
            TARGET,
            "--program",
            program.to_str().unwrap(),
            "--arg",
            "stado",
            "--arg",
            "byk-auth-worker",
            "--json",
        ])
        .stdin(Stdio::piped())
        .spawn()
        .expect("the built stado binary starts");
    child
        .stdin
        .take()
        .expect("the payload travels on stdin")
        .write_all(b"{\"bridgeToken\":\"real-value\"}\n")
        .expect("write the payload");
    let output = child.wait_with_output().expect("stado finishes");
    assert!(output.status.success(), "{}", said(&output));

    // The file the program itself wrote is the proof it ran here and read the
    // payload; the receipt is the product's account of the same run.
    assert_eq!(
        std::fs::read(&receipt_path).expect("the program left its output file"),
        b"{\"bridgeToken\":\"real-value\"}"
    );
    let report = receipt(&output);
    assert_eq!(report["status"], "exited");
    assert_eq!(report["exit_code"], 0);
    assert_eq!(
        report["stdout"],
        "worker:{\"bridgeToken\":\"real-value\"}\n"
    );
    assert_eq!(report["stderr"], "worker diagnostic\n");
    assert_eq!(
        report["arguments"].as_array().unwrap(),
        &[Value::from("stado"), Value::from("byk-auth-worker")]
    );
}

#[test]
fn a_termination_signal_reaches_the_attached_program() {
    let fixture = Fixture::new();
    let run = fixture.run("attached-signal");
    let ready = run.join("ready");
    let program = run.join("worker");
    executable(
        &program,
        &format!(
            "#!/bin/sh\ntrap \"printf 'forwarded-term\\\\n'; exit 42\" TERM\nprintf ready > {}\nwhile :; do sleep 1; done\n",
            ready.display()
        ),
    );

    let child = fixture
        .command(&[
            "host",
            "run-attached",
            TARGET,
            "--program",
            program.to_str().unwrap(),
        ])
        .spawn()
        .expect("the built stado binary starts");

    // The file the program writes on entry is what says it is running; only
    // then can the signal be about a live process.
    let deadline = Instant::now() + READY_TIMEOUT;
    while !ready.exists() && Instant::now() < deadline {
        std::thread::sleep(Duration::from_millis(10));
    }
    assert!(ready.exists(), "the attached program never started");

    nix::sys::signal::kill(
        nix::unistd::Pid::from_raw(child.id() as i32),
        nix::sys::signal::Signal::SIGTERM,
    )
    .expect("signal the stado process this test started");
    let output = child.wait_with_output().expect("stado finishes");

    // The program's own trap chose 42 and printed one line; both travelled
    // back through the attached channel.
    assert_eq!(output.status.code(), Some(42), "{}", stderr(&output));
    assert_eq!(String::from_utf8_lossy(&output.stdout), "forwarded-term\n");
}

#[test]
fn a_declared_cargo_build_leaves_its_binary_in_the_run_tree() {
    let fixture = Fixture::new();
    let run = fixture.run("build-success");
    let source = run.join("source");
    std::fs::create_dir_all(source.join("src")).unwrap();
    std::fs::write(
        source.join("Cargo.toml"),
        "[package]\nname = \"host-run-fixture\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        source.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"host-run-fixture\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(
        source.join("src/main.rs"),
        "fn main() { println!(\"built here\"); }\n",
    )
    .unwrap();

    let output = fixture.run_stado(&[
        "host",
        "build",
        TARGET,
        "--manifest-path",
        source.join("Cargo.toml").to_str().unwrap(),
        "--bin",
        "host-run-fixture",
        "--json",
    ]);
    assert!(output.status.success(), "{}", said(&output));
    let report = receipt(&output);
    assert_eq!(report["status"], "built");
    assert_eq!(report["exit_code"], 0);

    // The artifact the real Cargo left, and its own output when run.
    let binary = source.join("target/release/host-run-fixture");
    assert!(binary.is_file(), "the release binary is missing");
    let ran = std::process::Command::new(&binary)
        .output()
        .expect("the binary this build produced runs");
    assert_eq!(String::from_utf8_lossy(&ran.stdout), "built here\n");
}

#[test]
fn removing_a_run_directory_deletes_it_and_repeating_the_removal_settles() {
    let fixture = Fixture::new();
    let run = fixture.run("cleanup");
    std::fs::create_dir_all(run.join("source/nested")).unwrap();
    std::fs::write(run.join("source/nested/artifact"), b"bytes").unwrap();

    let removed = fixture.run_stado(&[
        "host",
        "remove-run-directory",
        TARGET,
        run.to_str().unwrap(),
        "--json",
    ]);
    assert!(removed.status.success(), "{}", said(&removed));
    assert_eq!(receipt(&removed)["status"], "removed");
    assert!(!run.exists(), "the run directory is still on disk");
    assert!(
        fixture.run_root().is_dir(),
        "the shared run root must survive one run's removal"
    );

    let again = fixture.run_stado(&[
        "host",
        "remove-run-directory",
        TARGET,
        run.to_str().unwrap(),
        "--json",
    ]);
    assert!(again.status.success(), "{}", said(&again));
    assert_eq!(receipt(&again)["status"], "absent");
}
